version: '3'
services:
 # Django app
  radarsys:
    container_name: 'radarsys'
    build: .
    restart: always
    image: radarsys
    ports:
      - 8000:8000
    env_file: .env
    links:
      - radarsys-postgres
    volumes:
      - './:/radarsys'
      - '${DOCKER_DATA}/static:/radarsys/static'
    labels:
      ofelia.enabled: "true"
      # ofelia.job-exec.restart-reception.schedule: "0 1/5 * * * *"
      ofelia.job-exec.test.schedule: "@every 5s"
      ofelia.job-exec.test.command: "python manage.py scheduler"
      # ofelia.job-exec.restart-pedestal.schedule: "0 2/10 * * * *"
      # ofelia.job-exec.restart-pedestal.command: "python manage.py restart_pedestal"
      # ofelia.job-exec.restart-experiment.schedule: "@midnight"
      # ofelia.job-exec.restart-experiment.command: "python manage.py restart_experiment"
    depends_on:
      - radarsys-postgres

  # PostgreSQL
  radarsys-postgres:
    container_name: 'radarsys-postgres'
    build: ./postgres/
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
     - 5432:5432
    expose:
      - 5432
    env_file: .env

  #Web Server
  radarsys-nginx:
    container_name: 'radarsys-nginx'
    restart: always
    build: ./nginx/
    ports:
      - '0.0.0.0:80:80'
    volumes_from:
      - radarsys
    links:
      - radarsys:radarsys
    depends_on:
      - radarsys

  #Ofelia Scheduler    
  radarsys-job:
    container_name: 'radarsys-job'
    image: mcuadros/ofelia:v0.3.6
    depends_on:
      - radarsys
    # networks:
    #   - backend_sirm
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: "12m"

volumes:
  pgdata:
    driver: local
