version: '3'
services:
 # Django app
  radarsys:
    container_name: 'radarsys'
    build: .
    restart: always
    image: radarsys
    ports:
      - 8000:8000
    env_file: .env
    links:
      - radarsys-postgres
    volumes:
      - './:/radarsys'
      - '${DOCKER_DATA}/static:/radarsys/static'
    depends_on:
      - radarsys-postgres

  # PostgreSQL
  radarsys-postgres:
    container_name: 'radarsys-postgres'
    build: ./postgres/
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
     - 5432:5432
    env_file: .env

  #Web Server
  radarsys-nginx:
    container_name: 'radarsys-nginx'
    restart: always
    build: ./nginx/
    ports:
      - '0.0.0.0:80:80'
    volumes_from:
      - radarsys
    links:
      - radarsys:radarsys
    depends_on:
      - radarsys

volumes:
  pgdata:
    driver: local
