version: '2'
services:
  web:
    container_name: 'radarsys_web'
    build: .
    restart: always
    image: radarsys
    command: gunicorn radarsys.wsgi:application -w 2 -b :8080
    env_file: .env
    ports:
      - "8080:8080"
    links:
      - redis
      - mysql
    volumes:
      - './:/data'
    depends_on:
      - redis
      - mysql

  redis:
    container_name: 'redis'
    image: 'redis:3.2-alpine'
    ports:
      - '127.0.0.1:6300:6379'
    volumes:
      - '/data/dockers/radarsys/redis:/data'

  celery_worker:
    image: radarsys
    env_file: .env
    command: celery -A radarsys worker -l info
    volumes_from:
      - web
    depends_on:
      - web

  mysql:
    container_name: 'mysql'
    image: 'mysql:5.6'
    env_file: .env
    ports:
      - '127.0.0.1:6301:3306'
    volumes:
      - '/data/dockers/radarsys/mysql:/var/lib/mysql'

  nginx:
    container_name: 'radarsys_nginx'
    restart: always
    build: ./nginx/
    ports:
      - "3000:80"
    volumes:
      - '/data/dockers/radarsys/nginx:/data/nginx'
    volumes_from:
      - web
    links:
      - web:web
    depends_on:
      - web
