# Generated by Django 2.2.1 on 2023-01-17 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('abs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABSConfiguration',
            fields=[
                ('configuration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Configuration')),
                ('active_beam', models.PositiveSmallIntegerField(default=0, verbose_name='Active Beam')),
                ('module_status', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=10000, verbose_name='Module Status')),
                ('operation_mode', models.PositiveSmallIntegerField(choices=[(0, 'Manual'), (1, 'Automatic')], default=0, verbose_name='Operation Mode')),
                ('operation_value', models.FloatField(blank=True, default='10', null=True, verbose_name='Periodic (seconds)')),
                ('module_messages', models.CharField(default='{"1": "Module 1", "2": "Module 2", "3": "Module 3", "4": "Module 4", "5": "Module 5", "6": "Module 6", "7": "Module 7", "8": "Module 8", "9": "Module 9", "10": "Module 10", "11": "Module 11", "12": "Module 12", "13": "Module 13", "14": "Module 14", "15": "Module 15", "16": "Module 16", "17": "Module 17", "18": "Module 18", "19": "Module 19", "20": "Module 20", "21": "Module 21", "22": "Module 22", "23": "Module 23", "24": "Module 24", "25": "Module 25", "26": "Module 26", "27": "Module 27", "28": "Module 28", "29": "Module 29", "30": "Module 30", "31": "Module 31", "32": "Module 32", "33": "Module 33", "34": "Module 34", "35": "Module 35", "36": "Module 36", "37": "Module 37", "38": "Module 38", "39": "Module 39", "40": "Module 40", "41": "Module 41", "42": "Module 42", "43": "Module 43", "44": "Module 44", "45": "Module 45", "46": "Module 46", "47": "Module 47", "48": "Module 48", "49": "Module 49", "50": "Module 50", "51": "Module 51", "52": "Module 52", "53": "Module 53", "54": "Module 54", "55": "Module 55", "56": "Module 56", "57": "Module 57", "58": "Module 58", "59": "Module 59", "60": "Module 60", "61": "Module 61", "62": "Module 62", "63": "Module 63", "64": "Module 64"}', max_length=10000, verbose_name='Modules Messages')),
            ],
            options={
                'db_table': 'abs_configurations',
            },
            bases=('main.configuration',),
        ),
        migrations.AddField(
            model_name='absbeam',
            name='abs_conf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abs.ABSConfiguration', verbose_name='ABS Configuration'),
        ),
        migrations.AddField(
            model_name='absactive',
            name='conf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abs.ABSConfiguration', verbose_name='ABS Configuration'),
        ),
    ]
