# Generated by Django 4.1.5 on 2023-01-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0002_auto_20230117_0948'),
        ('abs', '0002_initial'),
    ]

    operations = [
    ]
