# Generated by Django 2.2.1 on 2023-01-17 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USRPConfiguration',
            fields=[
                ('configuration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Configuration')),
            ],
            options={
                'db_table': 'usrp_configurations',
            },
            bases=('main.configuration',),
        ),
    ]
