"""
Django settings for radarsys project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xshb$k5fc-+j16)cvyffj&9u__0q3$l!hieh#+tbzqg)*f^km0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'polymorphic',
    'apps.accounts',
    'apps.main',
    'apps.misc',
    'apps.rc',
    'apps.dds',
    'apps.jars',
    'apps.usrp',
    'apps.abs',
    'apps.cgs',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'radarsys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates").replace('\\', '/'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'radarsys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'radarsys.sqlite'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'radarsys',
        'USER': 'developer',
        #'HOST': 'mysql',
        'PASSWORD': 'idi2015',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = None

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

MEDIA_ROOT = 'media'#os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/site_media/'

STATIC_URL = '/static/'
#STATIC_ROOT =  '/var/www/html/static/'
STATIC_ROOT = os.path.join(MEDIA_ROOT, 'static')

#STATICFILES_DIRS = (
#    os.path.join(BASE_DIR, 'apps', 'main', 'static'),
#
#)


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

FIXTURE_DIRS = (
    os.path.join(BASE_DIR, 'apps', 'rc', 'fixtures'),
    os.path.join(BASE_DIR, 'apps', 'main', 'fixtures'),
    os.path.join(BASE_DIR, 'apps', 'jars', 'fixtures'),
)

# Celery stuff
REDIS_HOST = 'redis'
BROKER_TRANSPORT = 'redis'
#--Development--# (Para Pruebas Locales)
BROKER_URL = 'redis://127.0.0.1:6300'
CELERY_RESULT_BACKEND = 'redis://localhost:6300'
#---------------#
#--Production---# (Para Docker)
#CELERY_BROKER_TRANSPORT = BROKER_URL = 'redis://%s:6379/0' % REDIS_HOST
#CELERY_RESULT_BACKEND = 'redis://%s:6379/0' % REDIS_HOST
#---------------#
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Lima'
