# Generated by Django 2.2.1 on 2023-01-17 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGSConfiguration',
            fields=[
                ('configuration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Configuration')),
                ('freq0', models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(450000000.0)], verbose_name='Frequency 0 (Hz)')),
                ('freq1', models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(450000000.0)], verbose_name='Frequency 1 (Hz)')),
                ('freq2', models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(450000000.0)], verbose_name='Frequency 2 (Hz)')),
                ('freq3', models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(450000000.0)], verbose_name='Frequency 3 (Hz)')),
            ],
            options={
                'db_table': 'cgs_configurations',
            },
            bases=('main.configuration',),
        ),
    ]
